[package]
name = "idw"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiff = "0.6.0"
image = "0.23.14"
csv = "1.0.0"
rust_decimal = "1.15.0"
ordered-float = "2.7.0"
